/**
 * Common English words with detailed Chinese translations
 * Format follows standard dictionary style:
 * "词性. 释义1，释义2；（语境）释义3，释义4..."
 */
export const COMMON_WORDS = new Map<string, string>([
    // Prepositions
    ["FOR", "prep. 为了，给；对于，关于；因为，由于；代表，代替；支持；持续（时间）"],
    ["TO", "prep. 到，向，朝；对于，关于；直到；属于；用于"],
    ["OF", "prep. ...的，属于；关于，对于；由...组成；表示所属关系"],
    ["IN", "prep. 在...里，在...内；用（语言、材料）；在...期间；穿着 adv. 在家，在内；流行"],
    ["ON", "prep. 在...上，关于；在（某天）；靠...支撑；一...就 adv. 继续，向前；穿着"],
    ["AT", "prep. 在（某处、时刻）；向，朝；以（速度、价格）；从事于"],
    ["BY", "prep. 通过，靠，用；在...旁边；由...创作；不迟于 adv. 经过，路过"],
    ["WITH", "prep. 和，同；用，以；随着；关于；具有，带有；尽管"],
    ["FROM", "prep. 从，来自；由...制成；因为，出于；距离"],
    ["INTO", "prep. 进入，到...里；成为，变成；撞上；对...有兴趣"],
    ["THROUGH", "prep. 穿过，通过；从始至终；凭借 adv. 自始至终；穿过"],
    ["OVER", "prep. 在...上方；越过，跨过；关于；超过 adv. 结束；翻倒；再一次"],
    ["UNDER", "prep. 在...下面；少于，低于；在...控制下；根据"],
    ["ABOVE", "prep. 在...上方；超过，胜过；高于 adv. 在上面；在前文"],
    ["BELOW", "prep. 在...下方；低于，少于；不及 adv. 在下面；在后文"],
    ["BETWEEN", "prep. 在...之间（两者）；介于...之间；往返于"],
    ["AMONG", "prep. 在...之中（三者以上）；...之一；在...中间"],

    // Conjunctions
    ["AND", "conj. 和，与，同；而且，并且；然后，接着；那么"],
    ["OR", "conj. 或者，还是；否则，要不然；即，也就是"],
    ["BUT", "conj. 但是，然而，可是；除了 prep. 除...以外"],
    ["NOR", "conj. 也不，也没有；既不...也不"],
    ["YET", "conj. 然而，但是 adv. 还，尚未；已经，还要；甚至"],
    ["SO", "conj. 所以，因此 adv. 如此，这么；非常；也"],
    ["THAN", "conj. 比，与其...不如；除...外"],
    ["THAT", "pron. 那个，那 conj. 因为；以至于；为了 det. 那，那个"],

    // Pronouns
    ["I", "pron. 我（主格第一人称单数）"],
    ["YOU", "pron. 你，你们（第二人称）"],
    ["HE", "pron. 他（第三人称单数阳性主格）"],
    ["SHE", "pron. 她（第三人称单数阴性主格）"],
    ["IT", "pron. 它（第三人称单数中性）；这，那；代指前文提到的事物"],
    ["WE", "pron. 我们（第一人称复数主格）"],
    ["THEY", "pron. 他们，她们，它们（第三人称复数）"],
    ["ME", "pron. 我（第一人称单数宾格）"],
    ["HIM", "pron. 他（第三人称单数阳性宾格）"],
    ["HER", "pron. 她（宾格）；她的（所有格）"],
    ["US", "pron. 我们（第一人称复数宾格）"],
    ["THEM", "pron. 他们，她们，它们（第三人称复数宾格）"],
    ["MY", "det. 我的（所有格）"],
    ["YOUR", "det. 你的，你们的（所有格）"],
    ["HIS", "det. 他的（所有格）"],
    ["ITS", "det. 它的（所有格）"],
    ["OUR", "det. 我们的（所有格）"],
    ["THEIR", "det. 他们的，她们的，它们的（所有格）"],
    ["MINE", "pron. 我的（名词性物主代词）"],
    ["YOURS", "pron. 你的，你们的（名词性物主代词）"],
    ["HERS", "pron. 她的（名词性物主代词）"],
    ["OURS", "pron. 我们的（名词性物主代词）"],
    ["THEIRS", "pron. 他们的（名词性物主代词）"],

    // Articles & Determiners
    ["THE", "art. 这个，那个，这些，那些（定冠词）；用于独一无二的事物"],
    ["A", "art. 一个，每一（不定冠词，用于辅音音素前）"],
    ["AN", "art. 一个（不定冠词，用于元音音素前）"],
    ["THIS", "det. 这，这个 pron. 这，这个，今"],
    ["THESE", "det. 这些 pron. 这些"],
    ["THOSE", "det. 那些 pron. 那些"],
    ["SOME", "det. 一些，某些；大约 pron. 一些人，一些"],
    ["ANY", "det. 任何，一些；丝毫 pron. 任何一个"],
    ["EACH", "det. 每个，各自的 pron. 每个，各自"],
    ["EVERY", "det. 每个，每一；所有的；最大的"],
    ["EITHER", "det. 任一的，两者之中任一的 pron. 两者之一"],
    ["NEITHER", "det. 两者都不的 pron. 两者都不"],

    // Auxiliary Verbs
    ["BE", "v. 是，在；成为，变成；存在；（用于构成被动语态、进行时）"],
    ["AM", "v. 是，在（be的第一人称单数现在式）"],
    ["IS", "v. 是，在（be的第三人称单数现在式）"],
    ["ARE", "v. 是，在（be的复数/第二人称现在式）"],
    ["WAS", "v. 是，在（be的第一/三人称单数过去式）"],
    ["WERE", "v. 是，在（be的复数/第二人称过去式；虚拟语气）"],
    ["BEING", "v. 存在，作为（be的现在分词）n. 存在；生物，人"],
    ["BEEN", "v. 是，在（be的过去分词）"],
    ["HAVE", "v. 有，拥有；吃，喝；进行，经历；使，让；必须"],
    ["HAS", "v. 有（have的第三人称单数现在式）"],
    ["HAD", "v. 有（have的过去式和过去分词）"],
    ["HAVING", "v. 有，拥有（have的现在分词）"],
    ["DO", "v. 做，干；进行；完成；处理；足够"],
    ["DOES", "v. 做（do的第三人称单数现在式）"],
    ["DID", "v. 做（do的过去式）"],
    ["DOING", "v. 做，进行（do的现在分词）n. 活动，行为"],
    ["DONE", "v. 做（do的过去分词）adj. 完成的；煮熟的；筋疲力尽的"],
    ["WILL", "modal v. 将要，会；愿意；总是 n. 意志，决心；遗嘱"],
    ["WOULD", "modal v. 将会，愿意；过去常常；大概"],
    ["SHALL", "modal v. 将，应该；必须；（征求意见）要不要"],
    ["SHOULD", "modal v. 应该，应当；可能，该；本应"],
    ["CAN", "modal v. 能够，可以；会 n. 罐头，容器"],
    ["COULD", "modal v. 可以，能够（can的过去式）；可能；请求"],
    ["MAY", "modal v. 可能，也许；可以，被允许；祝愿 n. 五月"],
    ["MIGHT", "modal v. 也许，可能（may的过去式）n. 力量，威力"],
    ["MUST", "modal v. 必须，一定；应当；很可能 n. 必须做的事"],

    // Common Adverbs
    ["NOT", "adv. 不，没有；并非，绝非"],
    ["NO", "adv. 不，否 adj. 没有，无；禁止 n. 否定，拒绝"],
    ["YES", "adv. 是，对，好 n. 是，同意"],
    ["NOW", "adv. 现在，如今；立刻，马上 conj. 既然，由于"],
    ["THEN", "adv. 那时，当时；然后，接着；那么，因此 adj. 当时的"],
    ["THERE", "adv. 那里，在那里；在那点上 pron. 用作引导词"],
    ["HERE", "adv. 这里，在这里；此时；这一点上 n. 这里"],
    ["UP", "adv. 向上，起来；完全地；增加 prep. 向上，沿着 adj. 向上的"],
    ["DOWN", "adv. 向下，下降；减少 prep. 沿着...而下 adj. 向下的；沮丧的"],
    ["OUT", "adv. 出去，在外；熄灭；出现 prep. 从...里面"],
    ["OFF", "adv. 离开，脱落；中断 prep. 从...离开 adj. 离开的；休息的"],
    ["AWAY", "adv. 离开，远离；消失，不在"],
    ["BACK", "adv. 返回，向后；回复 n. 背部；后面 v. 支持；后退"],
    ["MORE", "adv. 更，更多地 adj. 更多的，更大的 pron. 更多"],
    ["MOST", "adv. 最，非常；很 adj. 最多的，大部分的 pron. 大多数"],
    ["LESS", "adv. 较少地，更少地 adj. 更少的，较小的 prep. 减去"],
    ["LEAST", "adv. 最少，最小 adj. 最小的，最少的 pron. 最少的人或物"],
    ["VERY", "adv. 非常，很，极其；完全 adj. 正是，恰好；真正的"],
    ["TOO", "adv. 太，过度；也，还；非常"],
    ["ALSO", "adv. 也，而且；同样"],
    ["ONLY", "adv. 仅仅，只；刚刚 adj. 唯一的，仅有的 conj. 但是，不过"],
    ["JUST", "adv. 刚刚；仅仅，只是；正好；确实 adj. 公正的，公平的"],
    ["EVEN", "adv. 甚至，即使；还，更加 adj. 平的，平坦的；均等的；偶数的"],
    ["QUITE", "adv. 相当，颇；完全，十分；的确"],
    ["RATHER", "adv. 宁可，宁愿；相当，颇"],

    // Question Words
    ["WHO", "pron. 谁；...的人"],
    ["WHAT", "pron. 什么；多么 det. 什么，哪个；多少"],
    ["WHEN", "adv. 何时，什么时候 conj. 当...时；在...的时候"],
    ["WHERE", "adv. 哪里，在哪里 conj. 在...地方"],
    ["WHY", "adv. 为什么 n. 原因，理由"],
    ["HOW", "adv. 如何，怎样；多么，多少"],
    ["WHICH", "pron. 哪个，哪些 det. 哪一个；哪些"],

    // Common Short Words
    ["GO", "v. 去，走；进行，运转；变得；消失；（时间）流逝"],
    ["GET", "v. 得到，获得；变得；到达；理解；使，让"],
    ["GOT", "v. 得到（get的过去式和过去分词）"],
    ["SEE", "v. 看见，看到；理解，明白；经历；拜访，会见"],
    ["SAW", "v. 看见（see的过去式）n. 锯子 v. 锯"],
    ["SAY", "v. 说，讲；表明；假设；显示"],
    ["SAID", "v. 说（say的过去式和过去分词）adj. 上述的，所说的"],
    ["USE", "v. 使用，利用；消耗；对待 n. 使用；用途；效用"],
    ["USED", "v. 使用（use的过去式）adj. 习惯的；二手的，用过的"],
    ["NEW", "adj. 新的，崭新的；新鲜的；陌生的；新近的"],
    ["OLD", "adj. 旧的，老的；古老的；以前的；年长的"],
    ["BIG", "adj. 大的，巨大的；重要的；成功的；年长的"],
    ["SMALL", "adj. 小的，少的；不重要的；微弱的"],
    ["GOOD", "adj. 好的，优秀的；有益的；善良的 n. 好处；善行"],
    ["BAD", "adj. 坏的，不好的；有害的；严重的；腐败的"],
    ["HOT", "adj. 热的；辣的；流行的；激烈的；（脾气）暴躁的"],
    ["COLD", "adj. 冷的；冷淡的；客观的 n. 寒冷；感冒"],
    ["RUN", "v. 跑，奔跑；运转，运行；经营；流动 n. 跑步；行程"],
    ["RAN", "v. 跑（run的过去式）"],
    ["SIT", "v. 坐；位于；开会；适合"],
    ["SAT", "v. 坐（sit的过去式和过去分词）"],
    ["PUT", "v. 放，置；表达；估价；提交"],
    ["CUT", "v. 切，割；削减；穿过；缩短 n. 切口；削减；伤口"],
    ["LET", "v. 让，允许；出租；假设"],
    ["SET", "v. 设置，放置；树立；使处于某种状态 n. 一套，一组 adj. 固定的"],
    ["TWO", "num. 二，两个 n. 两个人或物"],
    ["TEN", "num. 十 n. 十个人或物"],
    ["ONE", "num. 一；单一 pron. 一个人或物 adj. 某一，唯一的"],
    ["SIX", "num. 六 n. 六个人或物"],
    ["ALL", "adj. 全部的，所有的 pron. 所有，全部 adv. 完全地；更加"],
    ["FEW", "adj. 很少的，几乎没有的 pron. 少数人或物"],
    ["OWN", "adj. 自己的 v. 拥有；承认 pron. 自己的东西"],

    // Conjunctive words
    ["IF", "conj. 如果；是否；即使 n. 条件，假设"],
    ["AS", "conj. 因为；当...时；虽然；按照 prep. 作为 adv. 同样地"],
    ["BECAUSE", "conj. 因为，由于"],
    ["SINCE", "conj. 自从...以来；因为，既然 prep. 自...以来 adv. 从那时起"],
    ["UNLESS", "conj. 除非，如果不"],
    ["UNTIL", "conj. 直到...为止 prep. 直到...时"],
    ["WHILE", "conj. 当...时；虽然，尽管 n. 一段时间"],
    ["ALTHOUGH", "conj. 虽然，尽管；然而"],
    ["THOUGH", "conj. 虽然，尽管 adv. 可是，然而"],
    ["WHEREAS", "conj. 然而，但是；鉴于，考虑到"],
    ["WHETHER", "conj. 是否；不管，无论"],

    // Additional common words
    ["ABOUT", "prep. 关于；大约，左右 adv. 大约；到处；周围"],
    ["AFTER", "prep. 在...之后；追求 conj. 在...之后 adv. 后来；以后"],
    ["AGAIN", "adv. 再次，又；另一方面；重新"],
    ["AGAINST", "prep. 反对，违反；靠，倚；对抗；不利于"],
    ["ALMOST", "adv. 几乎，差不多"],
    ["ALONE", "adj. 单独的，独自的；仅仅 adv. 独自地"],
    ["ALONG", "prep. 沿着，顺着 adv. 一起，一道；向前"],
    ["ALREADY", "adv. 已经，早已；竟然"],
    ["ALWAYS", "adv. 总是，一直；永远；一贯"],
    ["ANOTHER", "det. 另一个；又一 pron. 另一个人或物"],
    ["AROUND", "prep. 围绕；在...周围；大约 adv. 到处；周围；大约"],
    ["BEFORE", "prep. 在...之前；在...面前 conj. 在...之前 adv. 以前；从前"],
    ["BEHIND", "prep. 在...后面；落后于；支持 adv. 在后面；落后"],
    ["BESIDE", "prep. 在...旁边；与...相比"],
    ["BESIDES", "prep. 除...之外 adv. 此外，而且"],
    ["BOTH", "det. 两者都 pron. 两者，双方"],
    ["DURING", "prep. 在...期间；在...过程中"],
    ["ENOUGH", "adj. 足够的，充足的 adv. 足够地，充分地 pron. 足够，充分"],
    ["EVER", "adv. 曾经；永远；究竟；总是"],
    ["EVERYONE", "pron. 每个人，人人"],
    ["EVERYTHING", "pron. 一切，万事；最重要的东西"],
    ["EVERYWHERE", "adv. 到处，处处；各个地方"],
    ["EXCEPT", "prep. 除了，除...之外 conj. 除非；只是"],
    ["INSIDE", "prep. 在...里面；在...以内 adv. 在里面 n. 内部，里面"],
    ["INSTEAD", "adv. 代替，反而；却"],
    ["NOTHING", "pron. 没什么，没有东西；无关紧要的事 n. 无，零"],
    ["NOWHERE", "adv. 无处，任何地方都不"],
    ["OFTEN", "adv. 经常，时常；往往"],
    ["OUTSIDE", "prep. 在...外面；除了 adv. 在外面 n. 外部，外面"],
    ["PERHAPS", "adv. 也许，可能"],
    ["SEVERAL", "det. 几个，数个；各自的 pron. 几个人或物"],
    ["SOMEONE", "pron. 某人，有人"],
    ["SOMETHING", "pron. 某事，某物；重要的事"],
    ["SOMETIMES", "adv. 有时，间或"],
    ["SOMEWHERE", "adv. 某处，在某处"],
    ["STILL", "adv. 仍然，还；静止地；尽管如此 adj. 静止的，平静的"],
    ["SUCH", "det. 如此的，这样的 pron. 这样的人或物"],
    ["TOGETHER", "adv. 一起，共同；同时；连续地"],
    ["TOWARD", "prep. 朝向，面向；对于；为了；接近"],
    ["TOWARDS", "prep. 朝向，面向（toward的英式拼写）"],
    ["UPON", "prep. 在...上；基于；一...就"],
    ["WHATEVER", "pron. 无论什么，任何事物 det. 无论哪个"],
    ["WHENEVER", "conj. 每当，无论何时"],
    ["WHEREVER", "conj. 无论哪里，无论在何处"],
    ["WHOEVER", "pron. 无论谁，任何人"],
    ["WITHIN", "prep. 在...之内；在...内部；不超出"],
    ["WITHOUT", "prep. 没有，缺乏；在...外面"],
    ["YOURSELF", "pron. 你自己，你亲自"]
]);
